server:
  port: 8888
spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        git:
          uri: file:///J:\project\config
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    serviceUrl:
      default-zone: http://localhost:8761/eureka/

#eureka:
#  instance:
#    preferIpAddress: true
#    hostname: eureka-0
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    service-url:
#      default-zone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka