#spring:
#  datasource:
#    url: jdbc:mysql://mysql-standaloneservice:3306/mapping
#    username: root
#    password: La@456shitha
#    driver-class-name : com.mysql.cj.jdbc.Driver
#
#
#
#  jpa:
#    show-sql: true
#
#
#    hibernate:
#      ddl-auto: update
#
server:
  port: 8086


#base-url: http://localhost:9411/zipkin/
#base-url: http://localhost:9411/
spring:
#  zipkin:
#
#    enabled: true

  config:
    import: optional:configserver:http://localhost:8888

  application:
    name: mapping-demo-service



#eureka:
#  instance:
#    preferIpAddress: true
#    hostname: eureka-0
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    service-url:
#      default-zone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka





#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  metrics:
#    export:
#      prometheus:
#        enabled: true
#    health:
#      show-details: always
#  datasource:
#    url: jdbc:mysql://localhost:3306/mapping
#    username: root
#    password: La@456shitha
#    driver-class-name : com.mysql.cj.jdbc.Driver
  #cloud:
   # config:
    #  enabled: false


#  jpa:
#    show-sql: true

#
#    hibernate:
#      ddl-auto: update
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true




